/**
 * SaucerSwap Router ABI
 *
 * Full ABI for the SaucerSwap Router contract
 */

export const ROUTER_ABI = [
  {
    type: "constructor",
    stateMutability: "undefined",
    payable: false,
    inputs: [
      { type: "address", name: "_factory" },
      { type: "address", name: "_WHBAR" },
      { type: "address", name: "_feeCollector" },
      { type: "uint256", name: "_feeBips" },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "Approve",
    inputs: [
      { type: "address", name: "spender", indexed: true },
      { type: "uint64", name: "value", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "FeeTransfer",
    inputs: [
      { type: "address", name: "token", indexed: true },
      { type: "address", name: "to", indexed: true },
      { type: "uint256", name: "amount", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "Transfer",
    inputs: [
      { type: "address", name: "from", indexed: true },
      { type: "address", name: "to", indexed: true },
      { type: "uint64", name: "value", indexed: false },
    ],
  },
  {
    type: "function",
    name: "WHBAR",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "associateTokens",
    constant: false,
    payable: false,
    inputs: [{ type: "address[]", name: "tokens" }],
    outputs: [],
  },
  {
    type: "function",
    name: "dissociateTokens",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "token" }],
    outputs: [],
  },
  {
    type: "function",
    name: "factory",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "feeBips",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "feeCollector",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "getAmountIn",
    constant: true,
    stateMutability: "pure",
    payable: false,
    inputs: [
      { type: "uint256", name: "amountOut" },
      { type: "uint256", name: "reserveIn" },
      { type: "uint256", name: "reserveOut" },
    ],
    outputs: [{ type: "uint256", name: "amountIn" }],
  },
  {
    type: "function",
    name: "getAmountOut",
    constant: true,
    stateMutability: "pure",
    payable: false,
    inputs: [
      { type: "uint256", name: "amountIn" },
      { type: "uint256", name: "reserveIn" },
      { type: "uint256", name: "reserveOut" },
    ],
    outputs: [{ type: "uint256", name: "amountOut" }],
  },
  {
    type: "function",
    name: "getAmountsIn",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      { type: "uint256", name: "amountOut" },
      { type: "address[]", name: "path" },
    ],
    outputs: [{ type: "uint256[]", name: "amounts" }],
  },
  {
    type: "function",
    name: "getAmountsOut",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      { type: "uint256", name: "amountIn" },
      { type: "address[]", name: "path" },
    ],
    outputs: [{ type: "uint256[]", name: "amounts" }],
  },
  {
    type: "function",
    name: "owner",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "quote",
    constant: true,
    stateMutability: "pure",
    payable: false,
    inputs: [
      { type: "uint256", name: "amountA" },
      { type: "uint256", name: "reserveA" },
      { type: "uint256", name: "reserveB" },
    ],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "setFeeBips",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "_feeBips" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setFeeCollector",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_feeCollector" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setOwner",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_owner" }],
    outputs: [],
  },
  {
    type: "function",
    name: "swapETHForExactTokens",
    constant: false,
    stateMutability: "payable",
    payable: true,
    inputs: [
      { type: "uint256", name: "amountOut" },
      { type: "address[]", name: "path" },
      { type: "address", name: "to" },
      { type: "uint256", name: "deadline" },
    ],
    outputs: [{ type: "uint256[]", name: "amounts" }],
  },
  {
    type: "function",
    name: "swapExactETHForTokens",
    constant: false,
    stateMutability: "payable",
    payable: true,
    inputs: [
      { type: "uint256", name: "amountOutMin" },
      { type: "address[]", name: "path" },
      { type: "address", name: "to" },
      { type: "uint256", name: "deadline" },
    ],
    outputs: [{ type: "uint256[]", name: "amounts" }],
  },
  {
    type: "function",
    name: "swapExactETHForTokensSupportingFeeOnTransferTokens",
    constant: false,
    stateMutability: "payable",
    payable: true,
    inputs: [
      { type: "uint256", name: "amountOutMin" },
      { type: "address[]", name: "path" },
      { type: "address", name: "to" },
      { type: "uint256", name: "deadline" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "swapExactTokensForETH",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "amountIn" },
      { type: "uint256", name: "amountOutMin" },
      { type: "address[]", name: "path" },
      { type: "address", name: "to" },
      { type: "uint256", name: "deadline" },
    ],
    outputs: [{ type: "uint256[]", name: "amounts" }],
  },
  {
    type: "function",
    name: "swapExactTokensForETHSupportingFeeOnTransferTokens",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "amountIn" },
      { type: "uint256", name: "amountOutMin" },
      { type: "address[]", name: "path" },
      { type: "address", name: "to" },
      { type: "uint256", name: "deadline" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "swapExactTokensForTokens",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "amountIn" },
      { type: "uint256", name: "amountOutMin" },
      { type: "address[]", name: "path" },
      { type: "address", name: "to" },
      { type: "uint256", name: "deadline" },
    ],
    outputs: [{ type: "uint256[]", name: "amounts" }],
  },
  {
    type: "function",
    name: "swapExactTokensForTokensSupportingFeeOnTransferTokens",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "amountIn" },
      { type: "uint256", name: "amountOutMin" },
      { type: "address[]", name: "path" },
      { type: "address", name: "to" },
      { type: "uint256", name: "deadline" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "swapTokensForExactETH",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "amountOut" },
      { type: "uint256", name: "amountInMax" },
      { type: "address[]", name: "path" },
      { type: "address", name: "to" },
      { type: "uint256", name: "deadline" },
    ],
    outputs: [{ type: "uint256[]", name: "amounts" }],
  },
  {
    type: "function",
    name: "swapTokensForExactTokens",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "amountOut" },
      { type: "uint256", name: "amountInMax" },
      { type: "address[]", name: "path" },
      { type: "address", name: "to" },
      { type: "uint256", name: "deadline" },
    ],
    outputs: [{ type: "uint256[]", name: "amounts" }],
  },
  {
    type: "function",
    name: "tinycentsToTinybars",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "tinycents" }],
    outputs: [{ type: "uint256", name: "tinybars" }],
  },
  {
    type: "function",
    name: "whbar",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
] as const;
